# -*- coding: utf-8 -*-
"""Result.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHdc0owzbGGzPFXQLWk232_eop2PU1CI

### For our final code we decided to incorporate select few functions we created to showcase and leverage on the strengths of FuzzyWuzzy, Datasketch, and RapidFuzzy packages.
"""

import sys
import os
import pandas as pd
sys.path.append(os.path.abspath('.'))
sys.path.append(os.path.abspath('./src'))

"""#### Results obtained from FuzzyWuzzy package"""

# Get the processed left and right datasets for our project
from fuzzywuzzy_dataprep_vvs2115 import get_cleaned_datasets
left, right = get_cleaned_datasets()

# Import the CompanyMatcher Class created using FuzzyWhuzzy and the implemented functions
from fuzzywuzzy_vvs2115 import CompanyMatcher

# Instantiating a new instance of our Class:
matcher = CompanyMatcher()

# ClassMatcher that we created can be used for any 2 datasets with similar structures as our datasets.
# For our project we assign the relevant left and right datasets that we just processed
matcher.assign_data(left, right)

# This function allows to search for top "n" most likely matches for a particular id from left dataset:
matcher.get_most_similar_entities(14821, n=5)

# Run FuzzyWhuzzy matches for each id from the left dataset to return the highest match in the right dataset.
# You can run matches for all ids, or specify start, end, and interval windows.
# This function was used to get the final .csv file, but for the purposes of the demonstration,
# we indicated a smaller subset, otherwise it will take a lot of time to finish!
matcher.run_matches(0,5)

"""#### Results obtained from datasketch library. Run time ~ 6 mins"""

import datasketch_hgw2114

left_dataset_path = "data/left_dataset.csv"
right_dataset_path = "data/right_dataset.csv"
final_results = datasketch_hgw2114.main(left_dataset_path, right_dataset_path)

print("Total number of matches found: " + str(len(final_results)))
print("Here are the first 10 matches: ")
for match in final_results[:10]:
    print(match)

"""#### Results obtained from rapidfuzz library with a sample size test. Run time ~3 mins"""

# Get the processed left and right datasets for our project
from rapidfuzz_sample_kz2478 import find_matches_sample

#left = "data/left_cleaned_data_apr25.csv"
#right = "data/right_cleaned_data_apr25.csv"

# Run a test with 4000 sample size
find_matches_sample()